# Generated by Django 6.0 on 2026-01-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_user'),
        ('cart', '0007_add_cartitem_snapshot_fields'),
    ]

    operations = [
    ]
