# Generated by Django 6.0 on 2026-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, help_text='Minimum order amount for FREE delivery', max_digits=10)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Delivery charge if order is below min amount', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
